version: '3.1'

services:
  db:
    image: mysql
    container_name: ssii-agency-mysql
    privileged: true
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: SSII_AGENCY
    volumes:
      - ./storage:/var/lib/mysql